### PR TITLE
Mint signup form mockup

### PR DESCRIPTION
**Pull request by AsmaaShAli**
A signup form from Mint.com with similar functionality and appearance.

### CODE REVIEW

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but we need to fix the issues below before moving on ⬇️

- [x] Consider fixing the validator errors



- [x] It’s better to delete commented code on your HTML and CSS files.

- [x] Work on your Pull Request message. Follow this guideline that tells you how to do it. https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

[OPTIONAL]

- [x] Please be more descriptive with your commits, for example, you commit: "Minor adjustments" explain which changes you made.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by AsmaaShAli** [comment]
> ### Changes required recycle
> ### Hello team star2
> 
> Great work on this project, but we need to fix the issues below before moving on arrow_down
> 
>     * [x]  Consider fixing the validator errors
> 
> 
> 
> 
>     * [x]  It’s better to delete commented code on your HTML and CSS files.
> 
>     * [x]  Work on your Pull Request message. Follow this guideline that tells you how to do it. https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
> 
> 
> [OPTIONAL]
> 
>     * [x]  Please be more descriptive with your commits, for example, you commit: "Minor adjustments" explain which changes you made.
> 
> 
> _**After making the required changes please submit a new code review request**_
> Good luck! four_leaf_clover You are almost there! muscle
> 
> SofiBretz.

- We fixed the validation errors.
- Removed the commented code.
- and we understand your suggestions for descriptive commit messages, thanks.

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## Project looks amazing. Congratulation :+1: Approved.
One more thing is causing validator error, please fix it, before you merge to master:
* Please change `<meta charset="windows-1252" >`  to `<meta charset="UTF-8" />`
 
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
